### ISSUE TITLE
task retrieve modorganier-game_gamebryo.git failed

### ISSUE THREAD

**Issue by xarathos517** [LePresidente/modorganizer-umbrella#26]
See above. Full error message is:

```
2017-10-14 10:15:32,184 run task "retrieve modorganizer-game_gamebryo.git"
2017-10-14 10:15:32,184 Task retrieve modorganizer-game_gamebryo.git failed: [Error 267] The directory name is invalid
Traceback (most recent call last):
  File "C:\modorganizer-umbrella\unimake.py", line 374, in <module>
    exitcode = main()
  File "C:\modorganizer-umbrella\unimake.py", line 349, in main
    if task.process(progress):
  File "C:\modorganizer-umbrella\unibuild\modules\git.py", line 101, in process
    env=config['__environment'])
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 267] The directory name is invalid
```

**Comment by xarathos517** [comment]
Never mind. Progress folder had a 'completed modorganizer_super' entry, but had never actually done it. Task was failing because the folder didn't exist. Deleted text file, git retrieval works.
